// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/message.proto

package edu.brown.cs.systems.pubsub;

public final class PubSubProtos {
  private PubSubProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StringMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string message = 1;
    /**
     * <code>required string message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code pubsub.StringMessage}
   */
  public static final class StringMessage extends
      com.google.protobuf.GeneratedMessage
      implements StringMessageOrBuilder {
    // Use StringMessage.newBuilder() to construct.
    private StringMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringMessage defaultInstance;
    public static StringMessage getDefaultInstance() {
      return defaultInstance;
    }

    public StringMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_StringMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_StringMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.class, edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<StringMessage> PARSER =
        new com.google.protobuf.AbstractParser<StringMessage>() {
      public StringMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StringMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object message_;
    /**
     * <code>required string message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pubsub.StringMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.brown.cs.systems.pubsub.PubSubProtos.StringMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_StringMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_StringMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.class, edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.Builder.class);
      }

      // Construct using edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_StringMessage_descriptor;
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage getDefaultInstanceForType() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.getDefaultInstance();
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage build() {
        edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage buildPartial() {
        edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage result = new edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage) {
          return mergeFrom((edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage other) {
        if (other == edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          bitField0_ |= 0x00000001;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.brown.cs.systems.pubsub.PubSubProtos.StringMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string message = 1;
      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pubsub.StringMessage)
    }

    static {
      defaultInstance = new StringMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pubsub.StringMessage)
  }

  public interface ControlMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes topic_subscribe = 1;
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getTopicSubscribeList();
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    int getTopicSubscribeCount();
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    com.google.protobuf.ByteString getTopicSubscribe(int index);

    // repeated bytes topic_unsubscribe = 2;
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getTopicUnsubscribeList();
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    int getTopicUnsubscribeCount();
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    com.google.protobuf.ByteString getTopicUnsubscribe(int index);
  }
  /**
   * Protobuf type {@code pubsub.ControlMessage}
   */
  public static final class ControlMessage extends
      com.google.protobuf.GeneratedMessage
      implements ControlMessageOrBuilder {
    // Use ControlMessage.newBuilder() to construct.
    private ControlMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ControlMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ControlMessage defaultInstance;
    public static ControlMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ControlMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ControlMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                topicSubscribe_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              topicSubscribe_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                topicUnsubscribe_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              topicUnsubscribe_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          topicSubscribe_ = java.util.Collections.unmodifiableList(topicSubscribe_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          topicUnsubscribe_ = java.util.Collections.unmodifiableList(topicUnsubscribe_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_ControlMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_ControlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.class, edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ControlMessage> PARSER =
        new com.google.protobuf.AbstractParser<ControlMessage>() {
      public ControlMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ControlMessage> getParserForType() {
      return PARSER;
    }

    // repeated bytes topic_subscribe = 1;
    public static final int TOPIC_SUBSCRIBE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> topicSubscribe_;
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTopicSubscribeList() {
      return topicSubscribe_;
    }
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    public int getTopicSubscribeCount() {
      return topicSubscribe_.size();
    }
    /**
     * <code>repeated bytes topic_subscribe = 1;</code>
     */
    public com.google.protobuf.ByteString getTopicSubscribe(int index) {
      return topicSubscribe_.get(index);
    }

    // repeated bytes topic_unsubscribe = 2;
    public static final int TOPIC_UNSUBSCRIBE_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> topicUnsubscribe_;
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTopicUnsubscribeList() {
      return topicUnsubscribe_;
    }
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    public int getTopicUnsubscribeCount() {
      return topicUnsubscribe_.size();
    }
    /**
     * <code>repeated bytes topic_unsubscribe = 2;</code>
     */
    public com.google.protobuf.ByteString getTopicUnsubscribe(int index) {
      return topicUnsubscribe_.get(index);
    }

    private void initFields() {
      topicSubscribe_ = java.util.Collections.emptyList();
      topicUnsubscribe_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < topicSubscribe_.size(); i++) {
        output.writeBytes(1, topicSubscribe_.get(i));
      }
      for (int i = 0; i < topicUnsubscribe_.size(); i++) {
        output.writeBytes(2, topicUnsubscribe_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < topicSubscribe_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(topicSubscribe_.get(i));
        }
        size += dataSize;
        size += 1 * getTopicSubscribeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < topicUnsubscribe_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(topicUnsubscribe_.get(i));
        }
        size += dataSize;
        size += 1 * getTopicUnsubscribeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pubsub.ControlMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_ControlMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_ControlMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.class, edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.Builder.class);
      }

      // Construct using edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        topicSubscribe_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        topicUnsubscribe_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.internal_static_pubsub_ControlMessage_descriptor;
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage getDefaultInstanceForType() {
        return edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.getDefaultInstance();
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage build() {
        edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage buildPartial() {
        edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage result = new edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          topicSubscribe_ = java.util.Collections.unmodifiableList(topicSubscribe_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.topicSubscribe_ = topicSubscribe_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          topicUnsubscribe_ = java.util.Collections.unmodifiableList(topicUnsubscribe_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.topicUnsubscribe_ = topicUnsubscribe_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage) {
          return mergeFrom((edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage other) {
        if (other == edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage.getDefaultInstance()) return this;
        if (!other.topicSubscribe_.isEmpty()) {
          if (topicSubscribe_.isEmpty()) {
            topicSubscribe_ = other.topicSubscribe_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTopicSubscribeIsMutable();
            topicSubscribe_.addAll(other.topicSubscribe_);
          }
          onChanged();
        }
        if (!other.topicUnsubscribe_.isEmpty()) {
          if (topicUnsubscribe_.isEmpty()) {
            topicUnsubscribe_ = other.topicUnsubscribe_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTopicUnsubscribeIsMutable();
            topicUnsubscribe_.addAll(other.topicUnsubscribe_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.brown.cs.systems.pubsub.PubSubProtos.ControlMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes topic_subscribe = 1;
      private java.util.List<com.google.protobuf.ByteString> topicSubscribe_ = java.util.Collections.emptyList();
      private void ensureTopicSubscribeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          topicSubscribe_ = new java.util.ArrayList<com.google.protobuf.ByteString>(topicSubscribe_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTopicSubscribeList() {
        return java.util.Collections.unmodifiableList(topicSubscribe_);
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public int getTopicSubscribeCount() {
        return topicSubscribe_.size();
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public com.google.protobuf.ByteString getTopicSubscribe(int index) {
        return topicSubscribe_.get(index);
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public Builder setTopicSubscribe(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicSubscribeIsMutable();
        topicSubscribe_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public Builder addTopicSubscribe(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicSubscribeIsMutable();
        topicSubscribe_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public Builder addAllTopicSubscribe(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTopicSubscribeIsMutable();
        super.addAll(values, topicSubscribe_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_subscribe = 1;</code>
       */
      public Builder clearTopicSubscribe() {
        topicSubscribe_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated bytes topic_unsubscribe = 2;
      private java.util.List<com.google.protobuf.ByteString> topicUnsubscribe_ = java.util.Collections.emptyList();
      private void ensureTopicUnsubscribeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          topicUnsubscribe_ = new java.util.ArrayList<com.google.protobuf.ByteString>(topicUnsubscribe_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTopicUnsubscribeList() {
        return java.util.Collections.unmodifiableList(topicUnsubscribe_);
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public int getTopicUnsubscribeCount() {
        return topicUnsubscribe_.size();
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public com.google.protobuf.ByteString getTopicUnsubscribe(int index) {
        return topicUnsubscribe_.get(index);
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public Builder setTopicUnsubscribe(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicUnsubscribeIsMutable();
        topicUnsubscribe_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public Builder addTopicUnsubscribe(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicUnsubscribeIsMutable();
        topicUnsubscribe_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public Builder addAllTopicUnsubscribe(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTopicUnsubscribeIsMutable();
        super.addAll(values, topicUnsubscribe_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes topic_unsubscribe = 2;</code>
       */
      public Builder clearTopicUnsubscribe() {
        topicUnsubscribe_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pubsub.ControlMessage)
    }

    static {
      defaultInstance = new ControlMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pubsub.ControlMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pubsub_StringMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pubsub_StringMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pubsub_ControlMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pubsub_ControlMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/message.proto\022\006pubsu" +
      "b\" \n\rStringMessage\022\017\n\007message\030\001 \002(\t\"D\n\016C" +
      "ontrolMessage\022\027\n\017topic_subscribe\030\001 \003(\014\022\031" +
      "\n\021topic_unsubscribe\030\002 \003(\014B+\n\033edu.brown.c" +
      "s.systems.pubsubB\014PubSubProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pubsub_StringMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pubsub_StringMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pubsub_StringMessage_descriptor,
              new java.lang.String[] { "Message", });
          internal_static_pubsub_ControlMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pubsub_ControlMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pubsub_ControlMessage_descriptor,
              new java.lang.String[] { "TopicSubscribe", "TopicUnsubscribe", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
