// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/baggage_messages.proto

package edu.brown.cs.systems.baggage;

public final class BaggageMessages {
  private BaggageMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaggageMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .baggage.BaggageMessage.NamespaceData namespace = 1;
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> 
        getNamespaceList();
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData getNamespace(int index);
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    int getNamespaceCount();
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder> 
        getNamespaceOrBuilderList();
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder getNamespaceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code baggage.BaggageMessage}
   */
  public static final class BaggageMessage extends
      com.google.protobuf.GeneratedMessage
      implements BaggageMessageOrBuilder {
    // Use BaggageMessage.newBuilder() to construct.
    private BaggageMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaggageMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaggageMessage defaultInstance;
    public static BaggageMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaggageMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaggageMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                namespace_ = new java.util.ArrayList<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData>();
                mutable_bitField0_ |= 0x00000001;
              }
              namespace_.add(input.readMessage(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          namespace_ = java.util.Collections.unmodifiableList(namespace_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaggageMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaggageMessage>() {
      public BaggageMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaggageMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaggageMessage> getParserForType() {
      return PARSER;
    }

    public interface BagDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required bytes key = 1;
      /**
       * <code>required bytes key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required bytes key = 1;</code>
       */
      com.google.protobuf.ByteString getKey();

      // repeated bytes value = 2;
      /**
       * <code>repeated bytes value = 2;</code>
       */
      java.util.List<com.google.protobuf.ByteString> getValueList();
      /**
       * <code>repeated bytes value = 2;</code>
       */
      int getValueCount();
      /**
       * <code>repeated bytes value = 2;</code>
       */
      com.google.protobuf.ByteString getValue(int index);
    }
    /**
     * Protobuf type {@code baggage.BaggageMessage.BagData}
     *
     * <pre>
     * Mapping of key to several values 
     * </pre>
     */
    public static final class BagData extends
        com.google.protobuf.GeneratedMessage
        implements BagDataOrBuilder {
      // Use BagData.newBuilder() to construct.
      private BagData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private BagData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final BagData defaultInstance;
      public static BagData getDefaultInstance() {
        return defaultInstance;
      }

      public BagData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private BagData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                  mutable_bitField0_ |= 0x00000002;
                }
                value_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = java.util.Collections.unmodifiableList(value_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_BagData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_BagData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder.class);
      }

      public static com.google.protobuf.Parser<BagData> PARSER =
          new com.google.protobuf.AbstractParser<BagData>() {
        public BagData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BagData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<BagData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required bytes key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString key_;
      /**
       * <code>required bytes key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }

      // repeated bytes value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.util.List<com.google.protobuf.ByteString> value_;
      /**
       * <code>repeated bytes value = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getValueList() {
        return value_;
      }
      /**
       * <code>repeated bytes value = 2;</code>
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue(int index) {
        return value_.get(index);
      }

      private void initFields() {
        key_ = com.google.protobuf.ByteString.EMPTY;
        value_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, key_);
        }
        for (int i = 0; i < value_.size(); i++) {
          output.writeBytes(2, value_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, key_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < value_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(value_.get(i));
          }
          size += dataSize;
          size += 1 * getValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code baggage.BaggageMessage.BagData}
       *
       * <pre>
       * Mapping of key to several values 
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_BagData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_BagData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder.class);
        }

        // Construct using edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_BagData_descriptor;
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData getDefaultInstanceForType() {
          return edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.getDefaultInstance();
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData build() {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData buildPartial() {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData result = new edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = java.util.Collections.unmodifiableList(value_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData) {
            return mergeFrom((edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData other) {
          if (other == edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required bytes key = 1;
        private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public com.google.protobuf.ByteString getKey() {
          return key_;
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public Builder setKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }

        // repeated bytes value = 2;
        private java.util.List<com.google.protobuf.ByteString> value_ = java.util.Collections.emptyList();
        private void ensureValueIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            value_ = new java.util.ArrayList<com.google.protobuf.ByteString>(value_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
            getValueList() {
          return java.util.Collections.unmodifiableList(value_);
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public int getValueCount() {
          return value_.size();
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public com.google.protobuf.ByteString getValue(int index) {
          return value_.get(index);
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public Builder setValue(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public Builder addValue(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureValueIsMutable();
          value_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public Builder addAllValue(
            java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
          ensureValueIsMutable();
          super.addAll(values, value_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes value = 2;</code>
         */
        public Builder clearValue() {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:baggage.BaggageMessage.BagData)
      }

      static {
        defaultInstance = new BagData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:baggage.BaggageMessage.BagData)
    }

    public interface NamespaceDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required bytes key = 1;
      /**
       * <code>required bytes key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required bytes key = 1;</code>
       */
      com.google.protobuf.ByteString getKey();

      // repeated .baggage.BaggageMessage.BagData bag = 2;
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> 
          getBagList();
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData getBag(int index);
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      int getBagCount();
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder> 
          getBagOrBuilderList();
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder getBagOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code baggage.BaggageMessage.NamespaceData}
     *
     * <pre>
     * Mapping of a namespace to a BagData 
     * </pre>
     */
    public static final class NamespaceData extends
        com.google.protobuf.GeneratedMessage
        implements NamespaceDataOrBuilder {
      // Use NamespaceData.newBuilder() to construct.
      private NamespaceData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private NamespaceData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final NamespaceData defaultInstance;
      public static NamespaceData getDefaultInstance() {
        return defaultInstance;
      }

      public NamespaceData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private NamespaceData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  bag_ = new java.util.ArrayList<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData>();
                  mutable_bitField0_ |= 0x00000002;
                }
                bag_.add(input.readMessage(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            bag_ = java.util.Collections.unmodifiableList(bag_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_NamespaceData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_NamespaceData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder.class);
      }

      public static com.google.protobuf.Parser<NamespaceData> PARSER =
          new com.google.protobuf.AbstractParser<NamespaceData>() {
        public NamespaceData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new NamespaceData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<NamespaceData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required bytes key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString key_;
      /**
       * <code>required bytes key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes key = 1;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }

      // repeated .baggage.BaggageMessage.BagData bag = 2;
      public static final int BAG_FIELD_NUMBER = 2;
      private java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> bag_;
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> getBagList() {
        return bag_;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      public java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder> 
          getBagOrBuilderList() {
        return bag_;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      public int getBagCount() {
        return bag_.size();
      }
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData getBag(int index) {
        return bag_.get(index);
      }
      /**
       * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder getBagOrBuilder(
          int index) {
        return bag_.get(index);
      }

      private void initFields() {
        key_ = com.google.protobuf.ByteString.EMPTY;
        bag_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getBagCount(); i++) {
          if (!getBag(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, key_);
        }
        for (int i = 0; i < bag_.size(); i++) {
          output.writeMessage(2, bag_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, key_);
        }
        for (int i = 0; i < bag_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, bag_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code baggage.BaggageMessage.NamespaceData}
       *
       * <pre>
       * Mapping of a namespace to a BagData 
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_NamespaceData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_NamespaceData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder.class);
        }

        // Construct using edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getBagFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (bagBuilder_ == null) {
            bag_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            bagBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_NamespaceData_descriptor;
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData getDefaultInstanceForType() {
          return edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.getDefaultInstance();
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData build() {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData buildPartial() {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData result = new edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (bagBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              bag_ = java.util.Collections.unmodifiableList(bag_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.bag_ = bag_;
          } else {
            result.bag_ = bagBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData) {
            return mergeFrom((edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData other) {
          if (other == edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (bagBuilder_ == null) {
            if (!other.bag_.isEmpty()) {
              if (bag_.isEmpty()) {
                bag_ = other.bag_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureBagIsMutable();
                bag_.addAll(other.bag_);
              }
              onChanged();
            }
          } else {
            if (!other.bag_.isEmpty()) {
              if (bagBuilder_.isEmpty()) {
                bagBuilder_.dispose();
                bagBuilder_ = null;
                bag_ = other.bag_;
                bitField0_ = (bitField0_ & ~0x00000002);
                bagBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getBagFieldBuilder() : null;
              } else {
                bagBuilder_.addAllMessages(other.bag_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          for (int i = 0; i < getBagCount(); i++) {
            if (!getBag(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required bytes key = 1;
        private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public com.google.protobuf.ByteString getKey() {
          return key_;
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public Builder setKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }

        // repeated .baggage.BaggageMessage.BagData bag = 2;
        private java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> bag_ =
          java.util.Collections.emptyList();
        private void ensureBagIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            bag_ = new java.util.ArrayList<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData>(bag_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder> bagBuilder_;

        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> getBagList() {
          if (bagBuilder_ == null) {
            return java.util.Collections.unmodifiableList(bag_);
          } else {
            return bagBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public int getBagCount() {
          if (bagBuilder_ == null) {
            return bag_.size();
          } else {
            return bagBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData getBag(int index) {
          if (bagBuilder_ == null) {
            return bag_.get(index);
          } else {
            return bagBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder setBag(
            int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData value) {
          if (bagBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBagIsMutable();
            bag_.set(index, value);
            onChanged();
          } else {
            bagBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder setBag(
            int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder builderForValue) {
          if (bagBuilder_ == null) {
            ensureBagIsMutable();
            bag_.set(index, builderForValue.build());
            onChanged();
          } else {
            bagBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder addBag(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData value) {
          if (bagBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBagIsMutable();
            bag_.add(value);
            onChanged();
          } else {
            bagBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder addBag(
            int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData value) {
          if (bagBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBagIsMutable();
            bag_.add(index, value);
            onChanged();
          } else {
            bagBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder addBag(
            edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder builderForValue) {
          if (bagBuilder_ == null) {
            ensureBagIsMutable();
            bag_.add(builderForValue.build());
            onChanged();
          } else {
            bagBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder addBag(
            int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder builderForValue) {
          if (bagBuilder_ == null) {
            ensureBagIsMutable();
            bag_.add(index, builderForValue.build());
            onChanged();
          } else {
            bagBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder addAllBag(
            java.lang.Iterable<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData> values) {
          if (bagBuilder_ == null) {
            ensureBagIsMutable();
            super.addAll(values, bag_);
            onChanged();
          } else {
            bagBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder clearBag() {
          if (bagBuilder_ == null) {
            bag_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            bagBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public Builder removeBag(int index) {
          if (bagBuilder_ == null) {
            ensureBagIsMutable();
            bag_.remove(index);
            onChanged();
          } else {
            bagBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder getBagBuilder(
            int index) {
          return getBagFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder getBagOrBuilder(
            int index) {
          if (bagBuilder_ == null) {
            return bag_.get(index);  } else {
            return bagBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder> 
             getBagOrBuilderList() {
          if (bagBuilder_ != null) {
            return bagBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(bag_);
          }
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder addBagBuilder() {
          return getBagFieldBuilder().addBuilder(
              edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.getDefaultInstance());
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder addBagBuilder(
            int index) {
          return getBagFieldBuilder().addBuilder(
              index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.getDefaultInstance());
        }
        /**
         * <code>repeated .baggage.BaggageMessage.BagData bag = 2;</code>
         */
        public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder> 
             getBagBuilderList() {
          return getBagFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder> 
            getBagFieldBuilder() {
          if (bagBuilder_ == null) {
            bagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.BagDataOrBuilder>(
                    bag_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            bag_ = null;
          }
          return bagBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:baggage.BaggageMessage.NamespaceData)
      }

      static {
        defaultInstance = new NamespaceData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:baggage.BaggageMessage.NamespaceData)
    }

    // repeated .baggage.BaggageMessage.NamespaceData namespace = 1;
    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> namespace_;
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> getNamespaceList() {
      return namespace_;
    }
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    public java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder> 
        getNamespaceOrBuilderList() {
      return namespace_;
    }
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    public int getNamespaceCount() {
      return namespace_.size();
    }
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData getNamespace(int index) {
      return namespace_.get(index);
    }
    /**
     * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
     */
    public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder getNamespaceOrBuilder(
        int index) {
      return namespace_.get(index);
    }

    private void initFields() {
      namespace_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getNamespaceCount(); i++) {
        if (!getNamespace(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < namespace_.size(); i++) {
        output.writeMessage(1, namespace_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < namespace_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, namespace_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code baggage.BaggageMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.class, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.Builder.class);
      }

      // Construct using edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNamespaceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (namespaceBuilder_ == null) {
          namespace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          namespaceBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.brown.cs.systems.baggage.BaggageMessages.internal_static_baggage_BaggageMessage_descriptor;
      }

      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage getDefaultInstanceForType() {
        return edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.getDefaultInstance();
      }

      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage build() {
        edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage buildPartial() {
        edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage result = new edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage(this);
        int from_bitField0_ = bitField0_;
        if (namespaceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            namespace_ = java.util.Collections.unmodifiableList(namespace_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.namespace_ = namespace_;
        } else {
          result.namespace_ = namespaceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage) {
          return mergeFrom((edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage other) {
        if (other == edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.getDefaultInstance()) return this;
        if (namespaceBuilder_ == null) {
          if (!other.namespace_.isEmpty()) {
            if (namespace_.isEmpty()) {
              namespace_ = other.namespace_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNamespaceIsMutable();
              namespace_.addAll(other.namespace_);
            }
            onChanged();
          }
        } else {
          if (!other.namespace_.isEmpty()) {
            if (namespaceBuilder_.isEmpty()) {
              namespaceBuilder_.dispose();
              namespaceBuilder_ = null;
              namespace_ = other.namespace_;
              bitField0_ = (bitField0_ & ~0x00000001);
              namespaceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNamespaceFieldBuilder() : null;
            } else {
              namespaceBuilder_.addAllMessages(other.namespace_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getNamespaceCount(); i++) {
          if (!getNamespace(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .baggage.BaggageMessage.NamespaceData namespace = 1;
      private java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> namespace_ =
        java.util.Collections.emptyList();
      private void ensureNamespaceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          namespace_ = new java.util.ArrayList<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData>(namespace_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder> namespaceBuilder_;

      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> getNamespaceList() {
        if (namespaceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(namespace_);
        } else {
          return namespaceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public int getNamespaceCount() {
        if (namespaceBuilder_ == null) {
          return namespace_.size();
        } else {
          return namespaceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData getNamespace(int index) {
        if (namespaceBuilder_ == null) {
          return namespace_.get(index);
        } else {
          return namespaceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder setNamespace(
          int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData value) {
        if (namespaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespaceIsMutable();
          namespace_.set(index, value);
          onChanged();
        } else {
          namespaceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder setNamespace(
          int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder builderForValue) {
        if (namespaceBuilder_ == null) {
          ensureNamespaceIsMutable();
          namespace_.set(index, builderForValue.build());
          onChanged();
        } else {
          namespaceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder addNamespace(edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData value) {
        if (namespaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespaceIsMutable();
          namespace_.add(value);
          onChanged();
        } else {
          namespaceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder addNamespace(
          int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData value) {
        if (namespaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespaceIsMutable();
          namespace_.add(index, value);
          onChanged();
        } else {
          namespaceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder addNamespace(
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder builderForValue) {
        if (namespaceBuilder_ == null) {
          ensureNamespaceIsMutable();
          namespace_.add(builderForValue.build());
          onChanged();
        } else {
          namespaceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder addNamespace(
          int index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder builderForValue) {
        if (namespaceBuilder_ == null) {
          ensureNamespaceIsMutable();
          namespace_.add(index, builderForValue.build());
          onChanged();
        } else {
          namespaceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder addAllNamespace(
          java.lang.Iterable<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData> values) {
        if (namespaceBuilder_ == null) {
          ensureNamespaceIsMutable();
          super.addAll(values, namespace_);
          onChanged();
        } else {
          namespaceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder clearNamespace() {
        if (namespaceBuilder_ == null) {
          namespace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          namespaceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public Builder removeNamespace(int index) {
        if (namespaceBuilder_ == null) {
          ensureNamespaceIsMutable();
          namespace_.remove(index);
          onChanged();
        } else {
          namespaceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder getNamespaceBuilder(
          int index) {
        return getNamespaceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder getNamespaceOrBuilder(
          int index) {
        if (namespaceBuilder_ == null) {
          return namespace_.get(index);  } else {
          return namespaceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public java.util.List<? extends edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder> 
           getNamespaceOrBuilderList() {
        if (namespaceBuilder_ != null) {
          return namespaceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(namespace_);
        }
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder addNamespaceBuilder() {
        return getNamespaceFieldBuilder().addBuilder(
            edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.getDefaultInstance());
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder addNamespaceBuilder(
          int index) {
        return getNamespaceFieldBuilder().addBuilder(
            index, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.getDefaultInstance());
      }
      /**
       * <code>repeated .baggage.BaggageMessage.NamespaceData namespace = 1;</code>
       */
      public java.util.List<edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder> 
           getNamespaceBuilderList() {
        return getNamespaceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder> 
          getNamespaceFieldBuilder() {
        if (namespaceBuilder_ == null) {
          namespaceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceData.Builder, edu.brown.cs.systems.baggage.BaggageMessages.BaggageMessage.NamespaceDataOrBuilder>(
                  namespace_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          namespace_ = null;
        }
        return namespaceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:baggage.BaggageMessage)
    }

    static {
      defaultInstance = new BaggageMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:baggage.BaggageMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_baggage_BaggageMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_baggage_BaggageMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_baggage_BaggageMessage_BagData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_baggage_BaggageMessage_BagData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_baggage_BaggageMessage_NamespaceData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_baggage_BaggageMessage_NamespaceData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/protobuf/baggage_messages.pro" +
      "to\022\007baggage\"\275\001\n\016BaggageMessage\0228\n\tnamesp" +
      "ace\030\001 \003(\0132%.baggage.BaggageMessage.Names" +
      "paceData\032%\n\007BagData\022\013\n\003key\030\001 \002(\014\022\r\n\005valu" +
      "e\030\002 \003(\014\032J\n\rNamespaceData\022\013\n\003key\030\001 \002(\014\022,\n" +
      "\003bag\030\002 \003(\0132\037.baggage.BaggageMessage.BagD" +
      "ataB\036\n\034edu.brown.cs.systems.baggage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_baggage_BaggageMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_baggage_BaggageMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_baggage_BaggageMessage_descriptor,
              new java.lang.String[] { "Namespace", });
          internal_static_baggage_BaggageMessage_BagData_descriptor =
            internal_static_baggage_BaggageMessage_descriptor.getNestedTypes().get(0);
          internal_static_baggage_BaggageMessage_BagData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_baggage_BaggageMessage_BagData_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_baggage_BaggageMessage_NamespaceData_descriptor =
            internal_static_baggage_BaggageMessage_descriptor.getNestedTypes().get(1);
          internal_static_baggage_BaggageMessage_NamespaceData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_baggage_BaggageMessage_NamespaceData_descriptor,
              new java.lang.String[] { "Key", "Bag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
